import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Poppins } from "next/font/google";
import AuthProvider from "./api/auth/[...nextauth]/AuthProvider";
import { Toaster } from "@/components/ui/toaster";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Bekaspakai Indonesia",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="id" suppressHydrationWarning>
      <body
        className={`${poppins.className} antialiased mt-5 mx-10 md:mx-20 lg:mx-40 2xl:mx-80 scroll-smooth`}
      >
        <div>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <AuthProvider>
              {children}
            </AuthProvider>
          </ThemeProvider>
        </div>
        <Toaster />
      </body>
    </html >
  );
}
