import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import NavbarMenu from "@/containers/NavbarMenu";
import { Poppins } from "next/font/google";
import SearchBar from "@/containers/SearchBar";
import FooterBar from "@/containers/FooterBar";
import AuthProvider from "./api/auth/[...nextauth]/AuthProvider";
import ReduxProvider from "@/redux/ReduxProvider";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "BekasPakai",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased mt-5 mx-10 md:mx-20 lg:mx-40 2xl:mx-80`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            <ReduxProvider>
              <section className="space-y-5 mb-5">
                <NavbarMenu />
                <SearchBar />
              </section>
              {children}
              {/* <FooterBar /> */}
            </ReduxProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html >
  );
}
